### ISSUE TITLE
Multiple key presses with the Mele F10

### ISSUE THREAD

**Issue by Ben-Speakman** [Claudio-Sjo/HID_linux_xbmc_driver#3]
When running the learn mode with the F10 and pressing the mouse keys (left mouse and right mouse) I get multiple hits for the button press (which I assume is '01 01 00 00 00 00 00') and then a stream from what I assume is the air mouse activating. I have tried blacklisting the device in Xorg but always get multiple presses and only with these two keys. Do you have any suggestions on how I can get these keys to work?

```
Looking for Manufacturer : 1915
Looking for Product : af11
Found HID device at /dev/hidraw0
--- Vendor = 2.4G  Wireless Receiver
--- manufacturer = 1915, device = af11
Found HID device at /dev/hidraw1
--- Vendor = 2.4G  Wireless Receiver
--- manufacturer = 1915, device = af11
Found HID device at /dev/hidraw2
--- Vendor = 2.4G  Wireless Receiver
--- manufacturer = 1915, device = af11
Found HID device
Opened HID interface on /dev/hidraw0
Opened HID interface on /dev/hidraw1
Opened HID interface on /dev/hidraw2
01 01 00 00 00 00 00
01 01 00 00 00 00 00
01 01 00 00 00 00 00
01 00 00 00 00 00 00
01 00 00 10 00 00 00
01 00 00 10 00 00 00
01 00 00 00 00 00 00
01 00 00 20 00 00 00
01 00 ff 0f 00 00 00
01 00 ff 0f 00 00 00
01 00 00 20 00 00 00
01 00 ff 0f 00 00 00
01 00 00 20 00 00 00
01 00 ff 0f 00 00 00
etc
```

**Comment by Claudio-Sjo** [comment]
Hi,
I didn't even manage to get all keys on my remote to work.
There's nothing that the driver can do but receiving the codes.

**Comment by Ben-Speakman** [comment]
I thought as much. I ended up un-mapping those keys. Thanks for the great tool.
